name: CI
on: 
   push:
     branches: [ main ]
   workflow_dispatch:   
jobs:
   CI:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js 
          uses: actions/setup-node@v2.5.2
          with:
            node-version: 18.15.0
